In [1]:


import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
from sklearn.model_selection import train_test_split




import sys
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


from sklearn.ensemble import ExtraTreesClassifier, RandomForestClassifier
from gensim.models import KeyedVectors, Word2Vec

In [2]:
df_train=pd.read_csv('train.csv')
df_test=pd.read_csv('test.csv')

In [3]:
titles_train=df_train.title.values
titles_test=df_test.title.values

In [4]:
titles=list(titles_train)+list(titles_test)

In [5]:
# Simple tokenize
titles_list=[sentence.split() for sentence in titles]

In [6]:
ownvec=Word2Vec(titles_list, min_count=1, size=100)

In [7]:
ownvec.most_similar('iphone')

C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: Call to deprecated `most_similar` (Method will be removed in 4.0.0, use self.wv.most_similar() instead).
  """Entry point for launching an IPython kernel.


[('iphone6', 0.6916166543960571),
 ('apple', 0.6652277112007141),
 ('6s', 0.5983198881149292),
 ('iphone5s', 0.5731409788131714),
 ('iphone5', 0.5352137088775635),
 ('00.31.iphone', 0.5115038752555847),
 ('iphonex', 0.49824059009552),
 ('5s', 0.4963669776916504),
 ('space', 0.4938748776912689),
 ('fu', 0.49236932396888733)]

In [8]:
ownvec.most_similar('xiaomi')

C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: Call to deprecated `most_similar` (Method will be removed in 4.0.0, use self.wv.most_similar() instead).
  """Entry point for launching an IPython kernel.


[('xiomi', 0.8334578275680542),
 ('xioami', 0.7535781860351562),
 ('xiami', 0.6244704127311707),
 ('xiao', 0.5539789199829102),
 ('redmi', 0.5318061113357544),
 ('m4c', 0.5266726016998291),
 ('mi', 0.5178468823432922),
 ('huang', 0.5117055773735046),
 ('oppo', 0.4951171576976776),
 ('845', 0.4949208199977875)]

In [9]:
?ownvec

In [10]:
ownvec[['iphone','blue']]

C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  """Entry point for launching an IPython kernel.


array([[  3.79065347e+00,   2.65444312e-02,   3.36778831e+00,
         -2.54080832e-01,   5.07925034e-01,   6.94672108e-01,
          5.33774495e-01,  -3.13544536e+00,   1.63937712e+00,
         -5.01914835e+00,   2.70330024e+00,  -9.19160008e-01,
         -5.74738741e+00,   1.12294543e+00,  -7.48325944e-01,
          3.94104034e-01,   2.56436968e+00,   6.03464890e+00,
         -5.30166507e-01,   1.11989677e+00,   4.09447193e+00,
         -5.14073420e+00,  -1.34859872e+00,  -2.79977441e-01,
          3.09175897e+00,  -3.95023823e+00,   3.23656750e+00,
          4.36412907e+00,   3.98332500e+00,   3.92514968e+00,
          1.24428380e+00,   4.49939203e+00,  -2.27723765e+00,
          2.13103071e-01,  -2.90831387e-01,   3.52215266e+00,
          2.26592159e+00,   4.61572456e+00,   7.23726511e+00,
          1.97300300e-01,   1.42543650e+00,  -2.13246393e+00,
         -2.22664428e+00,  -6.83384955e-01,   5.61224461e+00,
          1.98081040e+00,  -6.96646273e-01,  -4.42677259e-01,
        

In [11]:
# So, I will use simple method for getting vectors. I will take each word in senctence and convert it to vector.
# After, will take mean at the end each sentence will be represented by vector.


In [12]:
a=np.array([[1,2,3],[2,3,4],[9,4,5]])

In [13]:
a

array([[1, 2, 3],
       [2, 3, 4],
       [9, 4, 5]])

In [14]:
a.mean(axis=0)

array([ 4.,  3.,  4.])

In [15]:
def convert_to_vec(text):
    text_list=text.split()
    vec=ownvec[text_list]
    vec=vec.mean(axis=0)
    return vec

In [16]:
train_w2v=df_train.title.apply(convert_to_vec)

C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  This is separate from the ipykernel package so we can avoid doing imports until


In [17]:
test_w2v=df_test.title.apply(convert_to_vec)

C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  This is separate from the ipykernel package so we can avoid doing imports until


In [18]:
# Now, let's convert it to dataframes and run similar simulations as we did for previous w2v (using available corpuses )

In [19]:
train_all=pd.DataFrame(train_w2v.values.tolist())
test_sub=pd.DataFrame(test_w2v.values.tolist())

In [20]:
train_all.columns

RangeIndex(start=0, stop=100, step=1)

In [21]:
# some linear models
from sklearn.linear_model import LogisticRegression, BayesianRidge

# SCM for classification
from sklearn.svm import SVC

from sklearn.pipeline import Pipeline

from sklearn.naive_bayes import MultinomialNB, GaussianNB, BernoulliNB

import warnings
warnings.filterwarnings('ignore')
np.random.seed(2019)
from sklearn.metrics import accuracy_score
from sklearn.model_selection import GridSearchCV

In [22]:
from sklearn.model_selection import train_test_split

In [23]:
df_train['Group']=df_train.image_path.map(lambda x: x[:7])
df_test['Group']=df_test.image_path.map(lambda x: x[:7])

In [24]:
train_all['Group']=df_train['Group']
train_all['Category']=df_train['Category']
test_sub['Group']=df_test['Group']


In [25]:
col=[i for i in range(100)]

In [26]:
train,test=train_test_split(train_all,random_state=2019,stratify=df_train.Category,test_size=0.2)


In [27]:
# let's build pipeline for parameter search in n_grams and and various models
lr=LogisticRegression()
nb=MultinomialNB()
svc=SVC()
# let's check first three and see which one is best
gnb=GaussianNB()
bnb=BernoulliNB()
br=BayesianRidge()
rf=RandomForestClassifier(n_estimators=150)

In [28]:
groups=['beauty_','mobile_','fashion']

In [31]:
from sklearn.neighbors import KNeighborsClassifier

In [32]:
from sklearn.svm import SVC

In [36]:
test_sub.shape

(172402, 101)

In [37]:
pipe_beauty=Pipeline([('model',RandomForestClassifier(n_estimators=280))])
pipe_mobile=Pipeline([('model',RandomForestClassifier(n_estimators=200))]) # I just choose lowest complexity
pipe_fashion=Pipeline([('model',RandomForestClassifier(n_estimators=300))])

pipe_en={'beauty_':pipe_beauty,'mobile_':pipe_mobile,'fashion':pipe_fashion}

pred_val={}
pred_test={}
for group in groups:
    print('Results for group:', group)
    X_train=train[train.Group==group][col]
    y_train=train[train.Group==group]['Category']
    model=pipe_en[group]
    model.fit(X_train,y_train)
    X_val=test[test.Group==group][col]
    y_val=test[test.Group==group]['Category']
    y_pred_val=model.predict(X_val)
    pred_val[group]=y_pred_val
    print('Accuracy for val set:', accuracy_score(y_val.values,y_pred_val))
    # Train for 100% of data
    X_train=train_all[train_all.Group==group][col]
    y_train=train_all[train_all.Group==group]['Category']
    X_test=test_sub[test_sub.Group==group][col]
    model.fit(X_train,y_train)
    pred_sub=model.predict(X_test)
    pred_test[group]=pred_sub
    


Results for group: beauty_
Accuracy for val set: 0.752324790202
Results for group: mobile_
Accuracy for val set: 0.776360517698
Results for group: fashion
Accuracy for val set: 0.601351812658


In [39]:
pipe_beauty=Pipeline([('model',RandomForestClassifier(n_estimators=280))])
pipe_mobile=Pipeline([('model',RandomForestClassifier(n_estimators=200))]) # I just choose lowest complexity
pipe_fashion=Pipeline([('model',RandomForestClassifier(n_estimators=300))])

pipe_en={'beauty_':pipe_beauty,'mobile_':pipe_mobile,'fashion':pipe_fashion}

pred_proba_val={}
pred_proba_test={}
for group in groups:
    print('Results for group:', group)
    X_train=train[train.Group==group][col]
    y_train=train[train.Group==group]['Category']
    model=pipe_en[group]
    model.fit(X_train,y_train)
    X_val=test[test.Group==group][col]
    y_val=test[test.Group==group]['Category']
    y_pred_proba_val=model.predict_proba(X_val)
    pred_proba_val[group]=y_pred_proba_val
    # Train for 100% of data
    X_train=train_all[train_all.Group==group][col]
    y_train=train_all[train_all.Group==group]['Category']
    X_test=test_sub[test_sub.Group==group][col]
    model.fit(X_train,y_train)
    pred_proba_sub=model.predict_proba(X_test)
    pred_proba_test[group]=pred_proba_sub
    


Results for group: beauty_
Results for group: mobile_
Results for group: fashion


In [54]:
 for group in groups:
    df=pd.DataFrame(pred_proba_val[group])
    col=pipe_en[group].classes_
    df.columns=col
    df['pred']=pred_val[group]
    df.to_csv(group+'_test_proba_w2v_own_val_data.csv',index=False)
    
    df=pd.DataFrame(pred_proba_test[group])
    df.columns=col
    df['pred']=pred_test[group]
    df.to_csv(group+'_test_proba_w2v_own_all_data.csv',index=False)