In [5]:


import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
from sklearn.model_selection import train_test_split




import sys
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


from sklearn.ensemble import ExtraTreesClassifier, RandomForestClassifier
from gensim.models import KeyedVectors, Word2Vec

In [3]:
df_train=pd.read_csv('train.csv')
df_test=pd.read_csv('test.csv')

In [15]:
titles_train=df_train.title.values
titles_test=df_test.title.values

In [16]:
titles=list(titles_train)+list(titles_test)

In [21]:
# Simple tokenize
titles_list=[sentence.split() for sentence in titles]

In [24]:
ownvec=Word2Vec(titles_list, min_count=1, size=100)

In [25]:
ownvec.most_similar('iphone')

C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: Call to deprecated `most_similar` (Method will be removed in 4.0.0, use self.wv.most_similar() instead).
  """Entry point for launching an IPython kernel.


[('iphone6', 0.6657751798629761),
 ('apple', 0.6317652463912964),
 ('6s', 0.5775070190429688),
 ('iphone5', 0.5394953489303589),
 ('iphone5s', 0.520264208316803),
 ('iphone7', 0.5031808018684387),
 ('5s', 0.4908602237701416),
 ('space', 0.4820113778114319),
 ('iphonr', 0.4725496768951416),
 ('s.d', 0.4604586064815521)]

In [28]:
ownvec.most_similar('xiaomi')

C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: Call to deprecated `most_similar` (Method will be removed in 4.0.0, use self.wv.most_similar() instead).
  """Entry point for launching an IPython kernel.


[('xiomi', 0.7986404895782471),
 ('xioami', 0.728898286819458),
 ('xiami', 0.6430413722991943),
 ('xiao', 0.5693444013595581),
 ('xiamo', 0.5638852715492249),
 ('redmi', 0.5541954636573792),
 ('085243150189xiaomi', 0.5467475652694702),
 ('1.xiaomi', 0.5161422491073608),
 ('doogee', 0.5115476846694946),
 ('m4c', 0.5090606212615967)]

In [29]:
?ownvec

In [34]:
ownvec[['iphone','blue']]

C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  """Entry point for launching an IPython kernel.


array([[-2.35269451, -0.88232023,  4.28360462, -2.31559587,  5.19785166,
         1.0419451 ,  4.55054903, -4.20807648, -2.70571089,  0.87956017,
         2.18833661, -3.08844066, -1.13650954,  4.71081448, -1.23350871,
         3.99396086,  3.63311648,  3.64615774, -2.7339251 ,  1.20853007,
        -5.17845201,  5.02592468,  0.47505632, -2.30003023,  2.77404261,
        -2.46304321, -3.18242264,  1.62645686, -2.09356022, -1.97014177,
         1.97379875,  1.64782584,  0.5239948 ,  2.82973146,  0.73931062,
        -4.43320847, -0.19685943,  4.71259785,  1.19712687, -1.20453203,
         0.93601644, -4.42389393,  1.96360624,  4.68813753,  0.03945253,
        -4.0955348 ,  5.48298502,  1.183851  , -1.68181753,  4.22733259,
         3.01435685, -5.39497089,  5.6279335 ,  2.23049927,  2.12210131,
        -0.96064937, -1.57263958, -2.46004462,  1.05247688,  0.47751582,
         5.17574072, -0.17458662,  1.03969741, -4.2940464 ,  1.22542787,
        -3.27647328,  1.81948185, -3.39889765, -0.2

In [35]:
# So, I will use simple method for getting vectors. I will take each word in senctence and convert it to vector.
# After, will take mean at the end each sentence will be represented by vector.


In [41]:
a=np.array([[1,2,3],[2,3,4],[9,4,5]])

In [42]:
a

array([[1, 2, 3],
       [2, 3, 4],
       [9, 4, 5]])

In [45]:
a.mean(axis=0)

array([ 4.,  3.,  4.])

In [50]:
def convert_to_vec(text):
    text_list=text.split()
    vec=ownvec[text_list]
    vec=vec.mean(axis=0)
    return vec

In [52]:
train_w2v=df_train.title.apply(convert_to_vec)

C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  This is separate from the ipykernel package so we can avoid doing imports until


In [53]:
test_w2v=df_test.title.apply(convert_to_vec)

C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  This is separate from the ipykernel package so we can avoid doing imports until


In [59]:
# Now, let's convert it to dataframes and run similar simulations as we did for previous w2v (using available corpuses )

In [91]:
train_all=pd.DataFrame(train_w2v.values.tolist())
test_sub=pd.DataFrame(test_w2v.values.tolist())

In [94]:
train_all.columns

RangeIndex(start=0, stop=100, step=1)

In [117]:
# some linear models
from sklearn.linear_model import LogisticRegression, BayesianRidge

# SCM for classification
from sklearn.svm import SVC

from sklearn.pipeline import Pipeline

from sklearn.naive_bayes import MultinomialNB, GaussianNB, BernoulliNB

import warnings
warnings.filterwarnings('ignore')
np.random.seed(2019)
from sklearn.metrics import accuracy_score
from sklearn.model_selection import GridSearchCV

In [118]:
from sklearn.model_selection import train_test_split

In [119]:
df_train['Group']=df_train.image_path.map(lambda x: x[:7])
df_test['Group']=df_test.image_path.map(lambda x: x[:7])

In [120]:
train_all['Group']=df_train['Group']
train_all['Category']=df_train['Category']
test_sub['Group']=df_test['Group']


In [121]:
col=[i for i in range(100)]

In [122]:
train,test=train_test_split(train_all,random_state=2019,stratify=df_train.Category,test_size=0.2)


In [123]:
# let's build pipeline for parameter search in n_grams and and various models
lr=LogisticRegression()
nb=MultinomialNB()
svc=SVC()
# let's check first three and see which one is best
gnb=GaussianNB()
bnb=BernoulliNB()
br=BayesianRidge()
rf=RandomForestClassifier(n_estimators=150)

In [124]:
groups=['beauty_','mobile_','fashion']

In [125]:
param={'model':[lr,rf]} # Can't use nb because negative values
pipe=Pipeline([('model',lr)])
for group in groups:
    print('Results for group:', group)
    X_train=train[train.Group==group][col]
    y_train=train[train.Group==group]['Category']
    grid_search=GridSearchCV(pipe,param_grid=param)
    grid_search.fit(X_train,y_train)
    print('Best parameters: ',grid_search.best_params_)
    print('Best scores: ',grid_search.best_score_)
    

Results for group: beauty_
Best parameters:  {'model': RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=150, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)}
Best scores:  0.740593895301
Results for group: mobile_
Best parameters:  {'model': RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=150, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)}
Best scor

In [126]:
pipe=Pipeline([('model',RandomForestClassifier())])
param={'model__n_estimators':[i for i in range(100,300,20)]} # Can't use nb because negative values
for group in groups:
    print('Results for group:', group)
    X_train=train[train.Group==group][col]
    y_train=train[train.Group==group]['Category']
    grid_search=GridSearchCV(pipe,param_grid=param)
    grid_search.fit(X_train,y_train)
    print('Best parameters: ',grid_search.best_params_)
    print('Best scores: ',grid_search.best_score_)

Results for group: beauty_
Best parameters:  {'model__n_estimators': 280}
Best scores:  0.742107421074
Results for group: mobile_
Best parameters:  {'model__n_estimators': 280}
Best scores:  0.769773515768
Results for group: fashion
Best parameters:  {'model__n_estimators': 260}
Best scores:  0.588810942132


These are results from other notebook same code but param={'model__n_estimators':[i for i in range(100,301,50)]}
This is quite strange since upper code also passes through 200 but accuracy for mobile is lower
Results for group: beauty_
Best parameters:  {'model__n_estimators': 300}
Best scores:  0.741566564602
Results for group: mobile_
Best parameters:  {'model__n_estimators': 200}
Best scores:  0.770007406541
Results for group: fashion
Best parameters:  {'model__n_estimators': 300}
Best scores:  0.590739697658

# UPS! I just realize that I didn't train to whole dataset. So, 20% of my data was not used for training. I need to retrain just in case

In [128]:
train_all.shape,train.shape

((666615, 102), (533292, 102))

In [129]:
pipe=Pipeline([('model',RandomForestClassifier())])

param={'model__n_estimators':[i for i in range(200,301,20)]} # Can't use nb because negative values


for group in groups:
    print('Results for group:', group)
    X_train=train_all[train_all.Group==group][col]
    y_train=train_all[train_all.Group==group]['Category']
    grid_search=GridSearchCV(pipe,param_grid=param)
    grid_search.fit(X_train,y_train)
    print('Best parameters: ',grid_search.best_params_)
    print('Best scores: ',grid_search.best_score_)

Results for group: beauty_
Best parameters:  {'model__n_estimators': 300}
Best scores:  0.746834250461
Results for group: mobile_
Best parameters:  {'model__n_estimators': 300}
Best scores:  0.774446454188
Results for group: fashion
Best parameters:  {'model__n_estimators': 280}
Best scores:  0.595333679256


In [ ]:
pipe_beauty=Pipeline([('model',RandomForestClassifier(n_estimators=280))])
pipe_mobile=Pipeline([('model',RandomForestClassifier(n_estimators=200))]) # I just choose lowest complexity
pipe_fashion=Pipeline([('model',RandomForestClassifier(n_estimators=300))])

pipe_en={'beauty_':pipe_beauty,'mobile_':pipe_mobile,'fashion':pipe_fashion}
for group in groups:
    print('Results for group:', group)
    X_train=train[train.Group==group][col]
    y_train=train[train.Group==group]['Category']
    grid_search=GridSearchCV(pipe,param_grid=param)
    grid_search.fit(X_train,y_train)
    print('Best parameters: ',grid_search.best_params_)
    print('Best scores: ',grid_search.best_score_)