In [1]:


import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
from sklearn.model_selection import train_test_split




import sys
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


from sklearn.ensemble import ExtraTreesClassifier, RandomForestClassifier
from gensim.models import KeyedVectors, Word2Vec

In [2]:
df_train=pd.read_csv('train.csv')
df_test=pd.read_csv('test.csv')

In [3]:
titles_train=df_train.title.values
titles_test=df_test.title.values

In [4]:
titles=list(titles_train)+list(titles_test)

In [5]:
# Simple tokenize
titles_list=[sentence.split() for sentence in titles]

In [6]:
ownvec=Word2Vec(titles_list, min_count=1, size=100)

In [7]:
ownvec.most_similar('iphone')

C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: Call to deprecated `most_similar` (Method will be removed in 4.0.0, use self.wv.most_similar() instead).
  """Entry point for launching an IPython kernel.


[('iphone6', 0.6749932765960693),
 ('apple', 0.6426588892936707),
 ('6s', 0.5988683700561523),
 ('iphone5s', 0.5676454305648804),
 ('iphone5', 0.5269131064414978),
 ('iphone6s', 0.504159688949585),
 ('space', 0.4909469485282898),
 ('iphone7', 0.4864862561225891),
 ('iphonex', 0.4807239770889282),
 ('fu', 0.47887396812438965)]

In [8]:
ownvec.most_similar('xiaomi')

C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: Call to deprecated `most_similar` (Method will be removed in 4.0.0, use self.wv.most_similar() instead).
  """Entry point for launching an IPython kernel.


[('xiomi', 0.7872194051742554),
 ('xioami', 0.7525759935379028),
 ('xiami', 0.6166476607322693),
 ('1.xiaomi', 0.5754553079605103),
 ('xiao', 0.5702985525131226),
 ('redmi', 0.5638731718063354),
 ('some', 0.5432642698287964),
 ('xiaumi', 0.5414942502975464),
 ('mige', 0.5256900191307068),
 ('doogee', 0.5157318711280823)]

In [9]:
?ownvec

In [10]:
ownvec[['iphone','blue']]

C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  """Entry point for launching an IPython kernel.


array([[-3.40917611, -0.88356853,  1.91113651,  4.39788198, -2.76509666,
         5.93758631, -2.52062893, -0.45024979,  1.12675941, -0.45993486,
        -2.317276  , -1.7332145 ,  3.45065641,  4.33849335,  2.4610424 ,
        -3.03822708,  5.77282763,  0.5036943 ,  0.69750893, -0.25553238,
         4.8059516 ,  0.41690415,  1.43244135,  0.12774934,  3.10684371,
         2.80887508,  2.00957108, -0.92913431, -1.67483282,  3.1275692 ,
         1.56923902, -3.18451905, -4.74411631, -1.05796623,  4.3338604 ,
         5.05353355,  2.12251401, -0.52326435,  2.47421718, -1.52605796,
        -2.30572557, -3.79815364, -4.42818689, -0.1021914 ,  2.97000647,
         1.47992086, -0.32046288,  0.15975183, -2.42063498,  8.51349163,
        -2.69324374,  2.90819168, -5.3332634 ,  4.29422235, -0.14803994,
         2.58080339, -5.39954281,  2.22384334,  0.20324795, -4.25917721,
        -3.87629271, -2.72896814,  1.54231226,  2.09845757, -1.1099962 ,
         3.1279819 ,  1.25838041, -0.27395973,  4.0

In [11]:
# So, I will use simple method for getting vectors. I will take each word in senctence and convert it to vector.
# After, will take mean at the end each sentence will be represented by vector.


In [12]:
a=np.array([[1,2,3],[2,3,4],[9,4,5]])

In [13]:
a

array([[1, 2, 3],
       [2, 3, 4],
       [9, 4, 5]])

In [14]:
a.mean(axis=0)

array([ 4.,  3.,  4.])

In [15]:
def convert_to_vec(text):
    text_list=text.split()
    vec=ownvec[text_list]
    vec=vec.mean(axis=0)
    return vec

In [16]:
train_w2v=df_train.title.apply(convert_to_vec)

C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  This is separate from the ipykernel package so we can avoid doing imports until


In [17]:
test_w2v=df_test.title.apply(convert_to_vec)

C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  This is separate from the ipykernel package so we can avoid doing imports until


In [18]:
# Now, let's convert it to dataframes and run similar simulations as we did for previous w2v (using available corpuses )

In [19]:
train_all=pd.DataFrame(train_w2v.values.tolist())
test_sub=pd.DataFrame(test_w2v.values.tolist())

In [20]:
train_all.columns

RangeIndex(start=0, stop=100, step=1)

In [21]:
# some linear models
from sklearn.linear_model import LogisticRegression, BayesianRidge

# SCM for classification
from sklearn.svm import SVC

from sklearn.pipeline import Pipeline

from sklearn.naive_bayes import MultinomialNB, GaussianNB, BernoulliNB

import warnings
warnings.filterwarnings('ignore')
np.random.seed(2019)
from sklearn.metrics import accuracy_score
from sklearn.model_selection import GridSearchCV

In [22]:
from sklearn.model_selection import train_test_split

In [23]:
df_train['Group']=df_train.image_path.map(lambda x: x[:7])
df_test['Group']=df_test.image_path.map(lambda x: x[:7])

In [24]:
train_all['Group']=df_train['Group']
train_all['Category']=df_train['Category']
test_sub['Group']=df_test['Group']


In [25]:
col=[i for i in range(100)]

In [26]:
train,test=train_test_split(train_all,random_state=2019,stratify=df_train.Category,test_size=0.2)


In [27]:
# let's build pipeline for parameter search in n_grams and and various models
lr=LogisticRegression()
nb=MultinomialNB()
svc=SVC()
# let's check first three and see which one is best
gnb=GaussianNB()
bnb=BernoulliNB()
br=BayesianRidge()
rf=RandomForestClassifier(n_estimators=150)

In [28]:
groups=['beauty_','mobile_','fashion']

In [29]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [31]:

from nltk.corpus import stopwords
from tqdm import tqdm
ignore_words = set(stopwords.words('english')).union(set(stopwords.words('indonesian')))
print(len(ignore_words))

936


In [73]:
tf1=TfidfVectorizer()
tf2=TfidfVectorizer(stop_words=ignore_words)

In [74]:
tf1.fit_transform(df_train.title)

<666615x80055 sparse matrix of type '<class 'numpy.float64'>'
	with 5838779 stored elements in Compressed Sparse Row format>

In [75]:
tf1


TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.float64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), norm='l2', preprocessor=None, smooth_idf=True,
        stop_words=None, strip_accents=None, sublinear_tf=False,
        token_pattern='(?u)\\b\\w\\w+\\b', tokenizer=None, use_idf=True,
        vocabulary=None)

In [33]:
X=tf1.fit_transform(df_train.title)

In [34]:
df_train.title[1]

'etude house precious mineral any cushion pearl aura puff'

In [35]:
df = pd.DataFrame({'docId': [1,2,3], 
               'sent': ['This is the first sentence','This is the second sentence', 'This is the third sentence']})

In [36]:
df['sent']

0     This is the first sentence
1    This is the second sentence
2     This is the third sentence
Name: sent, dtype: object

In [37]:
df_train.loc[:2,'title']

0                 nyx sex bomb pallete natural palette
1    etude house precious mineral any cushion pearl...
2                             milani rose powder blush
Name: title, dtype: object

In [40]:
df_train.loc[0,'title']

'nyx sex bomb pallete natural palette'

In [41]:
a=tf1.transform([df_train.loc[0,'title']])
a.data

array([ 0.57508414,  0.39570905,  0.30926809,  0.26839054,  0.23615767,
        0.53781214])

In [42]:
X[0].data

array([ 0.26839054,  0.57508414,  0.53781214,  0.39570905,  0.23615767,
        0.30926809])

In [50]:
tf1.vocabulary_['nyx']

55136

In [67]:
tf1.transform(['bedak nyx']).data

array([ 0.78448933,  0.62014232])

In [51]:
?tf1

In [45]:
tf1.get_feature_names()

['00',
 '000',
 '0000',
 '00001059',
 '000019',
 '000022',
 '000023',
 '00005',
 '00006',
 '00009',
 '0001',
 '0002',
 '00033',
 '00034',
 '00037',
 '00039',
 '00049',
 '00051',
 '00054',
 '00055',
 '00057',
 '00058',
 '00059',
 '00062',
 '0007',
 '00072',
 '00076',
 '00077',
 '0008',
 '00083',
 '00084',
 '00085',
 '0009',
 '00099',
 '000k',
 '000mah',
 '000masih',
 '000ml',
 '000qid',
 '000rb',
 '001',
 '0010',
 '00100',
 '00102',
 '0011',
 '00118',
 '0012',
 '001206',
 '00125',
 '0013',
 '00132',
 '00133',
 '0014',
 '001459',
 '001472',
 '001474',
 '0016',
 '0017',
 '001982',
 '001au',
 '001nude',
 '002',
 '002007',
 '002008',
 '002009',
 '002033',
 '002034',
 '002064',
 '002065',
 '002066',
 '002067',
 '002068',
 '002070',
 '002075',
 '0021',
 '002159',
 '002163',
 '0022',
 '002235',
 '002256',
 '002285',
 '0023',
 '002301',
 '002310',
 '002314',
 '002335',
 '00234',
 '002488',
 '002490',
 '002492',
 '002493',
 '0025',
 '00250802011',
 '002593',
 '002595',
 '0026',
 '002602',
 '0026

In [149]:
X[295].data

array([ 0.26470877,  0.3363279 ,  0.43629414,  0.44519367,  0.43118215,
        0.49228527])

In [144]:
X[227].data

array([ 0.52331314,  0.85214046])

In [134]:
X[108].data

array([ 0.33454622,  0.36656482,  0.57772568,  0.6480294 ])

In [107]:
a.data

array([ 0.37363838,  0.31862132,  0.42067443,  0.26832282,  0.25709424,
        0.24816507,  0.20647284,  0.42603503,  0.39760593])

In [83]:
X[0].data.reshape(1,6)

array([[ 0.26839054,  0.57508414,  0.53781214,  0.39570905,  0.23615767,
         0.30926809]])

In [68]:
def convert_to_vec(text):
    text_list=text.split()
    vec=ownvec[text_list]
    vec=vec.mean(axis=0)
    return vec

array([-0.06383371,  0.23241322,  0.44324207,  0.99992758,  1.7779603 ,
        0.46004558, -0.19088989,  0.1138455 ,  0.66034794, -0.17949305,
        0.39584598, -0.6073975 ,  1.17828703,  0.58056158, -0.49239144,
        0.65956825, -0.42966673, -0.75115269,  0.77956539,  0.27815971,
       -0.8862949 , -1.59686553, -0.46536949, -0.00802994, -0.37946233,
       -2.73829913, -1.1827451 ,  0.75361699,  1.63330567,  0.33535704,
        0.80834776,  0.21545963, -0.74014872,  0.01875312,  1.26894534,
       -0.1407664 , -0.4243913 ,  1.00039279, -0.77011442,  0.0029666 ,
       -0.96649718,  1.45785844, -0.7913692 ,  1.58942521, -0.80739474,
       -0.4152    , -1.34261954, -1.31261933,  0.49320152, -0.71929711,
       -1.70337999,  1.9743067 ,  0.50930524, -1.33810949, -1.14952886,
        0.85805136, -0.46135271, -0.13354826,  0.44819227, -0.70387721,
       -0.13496195, -0.33868861, -0.82721758,  0.06503379,  0.51075238,
       -0.7181012 ,  1.19391143,  0.12046566, -1.26348686,  0.86

In [ ]:
def convert_to_vec_tf1(text):
    text_list=text.split()
    vec=ownvec[text_list]
    vec=vec.mean(axis=0)
    return vec

In [70]:
a=df_train.title[0]
print(a)

nyx sex bomb pallete natural palette


In [73]:
vec=ownvec[a.split()]

In [85]:
vec.shape

(6, 100)

In [91]:
np.dot(X[0].data,vec)/X[0].shape[0]

array([-0.09228167,  0.37621924,  0.75371286,  1.40962735,  2.98477279,
        0.74488353, -0.44762999,  0.12529722,  1.15010359, -0.05194533,
        0.91609321, -0.9280034 ,  2.21137156,  1.28806229, -0.81449326,
        1.26393981, -0.65002372, -1.23984016,  1.31741335,  0.53443272,
       -1.48355696, -2.59337845, -0.83538948,  0.06986738, -0.80235605,
       -5.08763372, -2.393212  ,  1.24712065,  2.69315344,  0.66584573,
        1.47789615,  0.52610401, -1.44112898,  0.09911259,  2.26995216,
       -0.22297823, -0.61939851,  1.90044345, -1.3428086 , -0.2012198 ,
       -1.39338091,  2.48223172, -1.38132236,  2.573167  , -1.45343548,
       -0.49032702, -2.32183068, -2.42991824,  0.54562984, -1.25654883,
       -2.76196114,  3.59227656,  1.06782152, -2.30130562, -1.87223332,
        1.32286191, -0.73916142,  0.11183052,  0.65889586, -1.37772678,
        0.02037513, -0.65558423, -1.38102598, -0.01914845,  0.94801443,
       -1.2469503 ,  2.26659311,  0.08791514, -1.99415978,  1.69

In [43]:
tf1.transform(df_train.title[:1])

<1x80055 sparse matrix of type '<class 'numpy.float64'>'
	with 6 stored elements in Compressed Sparse Row format>

In [125]:
param={'model':[lr,rf]} # Can't use nb because negative values
pipe=Pipeline([('model',lr)])
for group in groups:
    print('Results for group:', group)
    X_train=train[train.Group==group][col]
    y_train=train[train.Group==group]['Category']
    grid_search=GridSearchCV(pipe,param_grid=param)
    grid_search.fit(X_train,y_train)
    print('Best parameters: ',grid_search.best_params_)
    print('Best scores: ',grid_search.best_score_)
    

Results for group: beauty_
Best parameters:  {'model': RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=150, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)}
Best scores:  0.740593895301
Results for group: mobile_
Best parameters:  {'model': RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=150, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)}
Best scor

In [ ]:
pipe=Pipeline([('model',RandomForestClassifier())])
param={'model__n_estimators':[i for i in range(100,301,50)]} # Can't use nb because negative values
for group in groups:
    print('Results for group:', group)
    X_train=train[train.Group==group][col]
    y_train=train[train.Group==group]['Category']
    grid_search=GridSearchCV(pipe,param_grid=param)
    grid_search.fit(X_train,y_train)
    print('Best parameters: ',grid_search.best_params_)
    print('Best scores: ',grid_search.best_score_)

Results for group: beauty_
Best parameters:  {'model__n_estimators': 300}
Best scores:  0.741566564602
Results for group: mobile_
Best parameters:  {'model__n_estimators': 200}
Best scores:  0.770007406541
Results for group: fashion


In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer